### ISSUE TITLE
Loading harmonization model without data crashes

### ISSUE THREAD

**Issue by AbdulkadirA** [CBICA/NiBAx#170]
How to reproduce
1) Start `NiBAx` without loading data
2) Load a harmonization model
3) Click `Apply model to data set`

The application will crash.

**Comment by melhemr** [comment]
Do you mean after loading harmonization model and then clicking apply model button it crashes?

**Comment by AbdulkadirA** [comment]
> Do you mean after loading harmonization model and then clicking apply model button it crashes?

Yes, if no data set is loaded. I updated the description to also include the third step.

**Comment by ashishsingh18** [comment]
Should be a simple fix - just disable loading model button/clicking apply model button, if datamodel has no data.
