### ISSUE TITLE
Show data button error

### ISSUE THREAD

**Issue by melhemr** [CBICA/NiBAx#174]
1. Load data
2. Load harmonization model
3. Apply harmonization
4. Save to data button used
5. Show data button on Harmonization model 

Results in an error. Needs to be debugged

**Comment by AbdulkadirA** [comment]
What was the error message? It worked for me using the default data set and model.

**Comment by melhemr** [comment]
I have been unable to recreate the error message with my standard dataset, and the datasets I used for the WRAP presentation, so I believe it was a dataset issue. I'm going to close this issue.
