### ISSUE TITLE
Residuals produced during out-of-sample harmonization are not correct

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/NiBAx#227]
@melhemr Can you please add steps to reproduce this issue?

**Comment by melhemr** [comment]
1) Load /NiBAx/testing/Data/synthetic_MUSE_ROI_dataset.pkl.gz
2) Load iSTAGING MUSE harmonization model v1.3 from iSTAGING project on the cluster
3) Apply harmonization model to data
4) Click 'Add to DataFrame' button
5) Click 'Show Data'

The result is changing residuals and  missing residuals

**Comment by AbdulkadirA** [comment]
Fixed by #231
