### ISSUE TITLE
SPARE scores are not being calculated correctly

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/NiBAx#229]
@melhemr Can you please add steps to reproduce this issue?

**Comment by melhemr** [comment]
Using the following data:

data: ```/cbica/home/melhemr/comp_space/FTD_center/FTDcenter.pkl.gz```

harm_model: ```/cbica/projects/ISTAGING/Pipelines/ISTAGING_Data_Consolidation_2020/v1.3/MUSE_harmonization_model.pkl```

spare_model: ```/cbica/projects/ISTAGING/Pipelines/ISTAGING_Data_Consolidation_2020/v1.3/SPARE_model_LIN-SVM_single_MUSE_ROIs_RES.pkl.gz```

1) Load data into NiBAx

2) Load harm_model into harmonization module

3) Apply harm_model to data

4) Click 'Add to DataFrame' button

5) Load spare_model in SPAREs module

6) Apply spare_model to data

7) Click 'Add to DataFrame' button

8) Check 'SPARE_BA' and 'SPARE_AD' in AgeTrends module

The trends follow no pattern based on age at all, which is not correct

**Comment by melhemr** [comment]
Closed by c336b630099a4a3c4edb1fbdea42dee27e4cfbdd
