### ISSUE TITLE
When clicking the 'add to dataframe' button in the SPAREs plugin, many datapoints are lost and not plotted

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/NiBAx#230]
@melhemr can you please add steps to reproduce this issue?

**Comment by melhemr** [comment]
Using the following files:
Data: ```/cbica/home/melhemr/comp_space/FTD_center/FTDcenter_withukbb2.pkl.gz```

harm_model: ```/cbica/projects/ISTAGING/Pipelines/ISTAGING_Data_Consolidation_2020/v1.3/MUSE_harmonization_model.pkl```

spare_model: ```/cbica/projects/ISTAGING/Pipelines/ISTAGING_Data_Consolidation_2020/v1.3/SPARE_model_LIN-SVM_single_MUSE_ROIs_RES.pkl.gz```


1) Load data into nibax

2) Load harm_model into harmonization module

3) Apply harm_model to data

4) Click 'Add to DataFrame' button

5) Load spare_model in SPAREs module

6) Apply spare_model to data

7) Click 'Add to DataFrame' button

8) Show plot with Hue = SITE

Very few UKBIOBANK2 participants remain in SPARE plot

**Comment by AbdulkadirA** [comment]
Related to #231

**Comment by AbdulkadirA** [comment]
Related to #231

**Comment by melhemr** [comment]
Fixed by c336b630099a4a3c4edb1fbdea42dee27e4cfbdd
